apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bwevent-frontend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "5"
    spec:
      containers:
        - image: europe-west1-docker.pkg.dev/PROJECT_ID/bwevent/frontend:IMAGE_TAG
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.5"
              memory: "256Mi"
